"""create diet plans table

Revision ID: 3ca6ab03fa33
Revises: 1e7b4a50aa5c
Create Date: 2026-02-08 22:23:57.127816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ca6ab03fa33'
down_revision: Union[str, Sequence[str], None] = '1e7b4a50aa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('diet_type', sa.String(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_plans_id'), 'diet_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diet_plans_id'), table_name='diet_plans')
    op.drop_table('diet_plans')
    # ### end Alembic commands ###
